# Migration And Default Risk

This notebook reproduces the main results for the Gaussian migration and default-risk case study.

In [1]:
from pathlib import Path
import sys
import pandas as pd
project_root = Path.cwd().resolve()
if not (project_root / 'src').exists():
    project_root = project_root.parent
sys.path.insert(0, str(project_root / 'src'))
import analysis
results = analysis.run_analysis()

## Validation

In [2]:
results['validation']

                      Item     Value
0  BBB default probability  0.001680
1    BBB default threshold -2.932726

## Convergence Check

In [3]:
results['convergence']

,N,VaR99.5_seed_42,VaR99.5_seed_43,VaR99.5_seed_44,Range,Relative Range
0,50000,300.088992,300.088992,307.409178,7.320186,0.024197
1,100000,307.409178,300.088992,300.088992,7.320186,0.024197
2,200000,300.088992,307.409178,307.409178,7.320186,0.024003
3,300000,300.088992,300.088992,300.088992,0.000000,0.000000

## Question 1 Risk Metrics

In [4]:
results['q1']

,Portfolio,Rho,Expected Value,90% VaR,99.5% VaR,90% ES,99.5% ES
0,Portfolio I,0%,1499.946037,5.884884,24.830730,11.706821,43.963197
1,Portfolio I,33%,1499.947626,6.762133,33.794513,12.883585,59.400739
2,Portfolio I,66%,1499.969151,5.884884,37.496420,14.341866,68.923257
3,Portfolio I,100%,1499.978108,-1.421938,49.974574,0.500335,87.153578
4,Portfolio II,0%,1499.805807,48.468414,290.029707,107.885005,304.152959
5,Portfolio II,33%,1499.879236,48.468414,300.088992,112.367390,370.944723
6,Portfolio II,66%,1499.935543,48.468414,370.275806,123.570911,446.751515
7,Portfolio II,100%,1500.061183,48.468414,478.670725,144.317719,478.670725

## Question 2 Risk Metrics

In [5]:
results['q2']

,Portfolio,Rho,Expected Value,90% VaR,99.5% VaR,90% ES,99.5% ES
0,Portfolio I,0%,1499.962998,0.800551,2.215247,1.274437,2.590766
1,Portfolio I,33%,1499.963526,3.227934,16.830132,7.291175,24.029597
2,Portfolio I,66%,1499.968952,3.573517,31.239166,11.431757,52.268643
3,Portfolio I,100%,1499.978108,-1.421938,49.974574,0.500335,87.153578
4,Portfolio II,0%,1499.928686,6.510632,14.289829,9.292519,16.440539
5,Portfolio II,33%,1499.944908,32.693396,135.850498,65.442792,171.523031
6,Portfolio II,66%,1499.971684,38.481297,265.098138,108.037272,327.098020
7,Portfolio II,100%,1500.061183,48.468414,478.670725,144.317719,478.670725